language: node_js
dist: xenial
sudo: required
node_js:
  - '8'
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install

services:
  - xvfb

script:
  - npm run test
