name: Deploy horizontal-pager
on:
  push:
    branches: [ master ]

jobs:
  deploy-horizontal-pager:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # 7.0.0
        with:
          fetch-depth: 0
      - name: Find Commit Message # PHRASE_FOUND == deploy
        run: |
          BEFORE="${{ github.event.before }}"
          AFTER="${{ github.event.after }}"
          FOUND="false"
          if [[ "$BEFORE" == "0000000000000000000000000000000000000000" ]]; then
            echo "Initial push, skipping commit scan"
          elif git log ${BEFORE}..${AFTER} --format="%s %b" | grep -qi "horizontal-pager@"; then
            FOUND="true"
          fi
          echo "PHRASE_FOUND=$FOUND" >> $GITHUB_ENV
      - name: Echo Status
        shell: bash
        run: |
          if [ "$PHRASE_FOUND" == "true" ]; then
            echo "DEPLOY HORIZONTAL-PAGER"
          else
            echo "SKIP DEPLOY HORIZONTAL-PAGER"
          fi
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # 6.4.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        if: env.PHRASE_FOUND == 'true'
        run: npm install -g npm@latest # ensure npm 11.5.1 or later
      - name: Install
        if: env.PHRASE_FOUND == 'true'
        run: npm ci
      - name: Publish horizontal-pager
        if: env.PHRASE_FOUND == 'true'
        run: |
          npm run build
          cd src/horizontal-pager
          npm publish --access public