name: Deploy horizontal-pager
on:
  push:
    branches: [ master ]

jobs:
  deploy-horizontal-pager:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
        with:
          fetch-depth: 0
      - name: Find Commit Message # PHRASE_FOUND == deploy
        run: |
          if git log origin/$GITHUB_REF_NAME..HEAD --format="%s %b" | grep -qi "horizontal-pager@"; then
            echo "PHRASE_FOUND=true" >> $GITHUB_ENV
          else
            echo "PHRASE_FOUND=false" >> $GITHUB_ENV
          fi
      - name: Echo Status
        shell: bash
        run: |
          if [ "$PHRASE_FOUND" == "true" ]; then
            echo "DEPLOY HORIZONTAL-PAGER"
          else
            echo "SKIP DEPLOY HORIZONTAL-PAGER"
          fi
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # 6.1.0
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Update npm
        if: env.PHRASE_FOUND == 'true'
        run: npm install -g npm@latest # ensure npm 11.5.1 or later
      - name: Install
        if: env.PHRASE_FOUND == 'true'
        run: npm ci
      - name: Publish horizontal-pager
        if: env.PHRASE_FOUND == 'true'
        run: |
          npm run build
          cd src/horizontal-pager
          npm publish --access public