name: Verify
on:
  pull_request:
    branches: [ master ]

jobs:
  verify:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Lint and Test
      run: xvfb-run -a npm test
